In [2]:
import pandas as pd # vamos a colocar los 6 archivos

In [3]:
path = '../Sesion2/data_retail'

path_customers = f'{path}/customers'
path_orders = f'{path}/orders'
path_order_items = f'{path}/order_items'
path_products = f'{path}/products'
path_categories = f'{path}/categories'
path_departments = f'{path}/departments'

In [4]:
df_customers = pd.read_csv(path_customers, sep='|', header=None) # para leer el archivo de clientes, el separador es |
df_orders = pd.read_csv(path_orders, sep='|', header=None)
df_order_items = pd.read_csv(path_order_items, sep='|', header=None)
df_products = pd.read_csv(path_products, sep='|', header=None)
df_categories = pd.read_csv(path_categories, sep='|', header=None, names =['category_id', 'category_department_id', 'category_name']) # para el archivo de categorias, le damos nombres a las columnas
df_departments = pd.read_csv(path_departments, sep='|', header=None, names =['department_id', 'department_name']) # para el archivo de departamentos, le damos nombres a las columnas

In [5]:
df_categories.head()

   category_id  category_department_id        category_name
0            1                       2             Football
1            2                       2               Soccer
2            3                       2  Baseball & Softball
3            4                       2           Basketball
4            5                       2             Lacrosse

In [6]:
df_departments

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
6              8          Sports

In [7]:
def validate_duplicated(df,column_name):
    if df[column_name].duplicated().any(): # si hay un duplicado se le coloca true, devuelve false porque no hay ningun duplicado en departments
        print("Hay duplicados en el dataframe en la columna",column_name)
        exit(1)
    else: 
        print("No existe duplicados")

In [8]:
def validate_departments(df):
    if df['department_name'].duplicated().any(): # si hay un duplicado se le coloca true, devuelve false porque no hay ningun duplicado en departments
        print("Hay departamentos duplicados en el dataframe")
        exit(1)
    else: 
        print("No existe duplicados")

In [9]:
validate_departments(df_departments)

No existe duplicados

In [10]:
validate_duplicated(df_departments,'department_name')

No existe duplicados

In [11]:
validate_duplicated(df_categories,'category_department_id')

Hay duplicados en el dataframe en la columna category_department_id

In [12]:
def validate_ids(df,valid_ids, column_name):
    if not df[column_name].isin(valid_ids).all(): #.any() # el all devuelve true si todos los elementos de este iterable son verdaderos
        # el any devuelve true si al menos un elemento de este iterable es verdadero
        print("Hay ids que no se encuentran en el dataframe")
    else: 
        print("Todo bien")

In [13]:
valid_ids = set(df_departments['department_id']) # creamos un conjunto con los ids de departamentos validos
valid_ids

{2, 3, 4, 5, 6, 7, 8}

In [14]:
if not df_categories['category_department_id'].isin(valid_ids).all(): #.any() # el all devuelve true si todos los elementos de este iterable son verdaderos
    # el any devuelve true si al menos un elemento de este iterable es verdadero
    print("Hay ids que no se encuentran en el dataframe")

In [15]:
validate_ids(df_categories,valid_ids,'category_department_id')

Todo bien

In [16]:
df_departments # conjunto A

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
6              8          Sports

In [17]:
df_categories.head() # conjunto B

   category_id  category_department_id        category_name
0            1                       2             Football
1            2                       2               Soccer
2            3                       2  Baseball & Softball
3            4                       2           Basketball
4            5                       2             Lacrosse

In [18]:
df_departments.merge(df_categories, left_on='department_id', right_on='category_department_id', how='left') # si lo dejamos asi, utiliza el inner join, pero si queremos un left join, se coloca how='left'
# df_departments.merge(df_categories, on=['department_id','product_id'], how='left')

,department_id,department_name,category_id,category_department_id,category_name
0,2,Fitness,1,2,Football
1,2,Fitness,2,2,Soccer
2,2,Fitness,3,2,Baseball & Softball
3,2,Fitness,4,2,Basketball
4,2,Fitness,5,2,Lacrosse
5,2,Fitness,6,2,Tennis & Racquet
6,2,Fitness,7,2,Hockey
7,2,Fitness,8,2,More Sports
8,3,Footwear,9,3,Cardio Equipment
9,3,Footwear,10,3,Strength Training
10,3,Footwear,11,3,Fitness Accessories
11,3,Footwear,12,3,Boxing & MMA
12,3,Footwear,13,3,Electronics
13,3,Footwear,14,3,Yoga & Pilates
14,3,Footwear,15,3,Training by Sport
15,3,Footwear,16,3,As Seen on TV!
16,4,Apparel,17,4,Cleats
17,4,Apparel,18,4,Men's Footwear
18,4,Apparel,19,4,Women's Footwear
19,4,Apparel,20,4,Kids' Footwear
20,4,Apparel,21,4,Featured Shops
21,4,Apparel,22,4,Accessories
22,5,Golf,23,5,Men's Apparel
23,5,Golf,24,5,Women's Apparel
24,5,Golf,25,5,Boys' Apparel
25,5,Golf,26,5,Girls' Apparel
26,5,Golf,27,5,Accessories
27,5,Golf,28,5,Top Brands
28,5,Golf,29,5,Shop By Sport
29,6,Outdoors,30,6,Men's Golf Clubs
30,6,Outdoors,31,6,Women's Golf Clubs
31,6,Outdoors,32,6,Golf Apparel
32,6,Outdoors,33,6,Golf Shoes
33,6,Outdoors,34,6,Golf Bags & Carts
34,6,Outdoors,35,6,Golf Gloves
35,6,Outdoors,36,6,Golf Balls
36,6,Outdoors,37,6,Electronics
37,6,Outdoors,38,6,Kids' Golf Clubs
38,6,Outdoors,39,6,Team Shop
39,6,Outdoors,40,6,Accessories
40,6,Outdoors,41,6,Trade-In
41,7,Fan Shop,42,7,Bike & Skate Shop
42,7,Fan Shop,43,7,Camping & Hiking
43,7,Fan Shop,44,7,Hunting & Shooting
44,7,Fan Shop,45,7,Fishing
45,7,Fan Shop,46,7,Indoor/Outdoor Games
46,7,Fan Shop,47,7,Boating
47,7,Fan Shop,48,7,Water Sports
48,8,Sports,49,8,MLB
49,8,Sports,50,8,NFL
50,8,Sports,51,8,NHL
51,8,Sports,52,8,NBA
52,8,Sports,53,8,NCAA
53,8,Sports,54,8,MLS
54,8,Sports,55,8,International Soccer
55,8,Sports,56,8,World Cup Shop
56,8,Sports,57,8,MLB Players
57,8,Sports,58,8,NFL Players

In [19]:
df_departments.to_csv('departments.csv', index=False)

In [20]:
df_departments.to_json('departments.json', orient='records', indent=2)

In [23]:
import sqlalchemy as db 
import pandas as pd

In [24]:
engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3310/retail_db')
try:
    conexion = engine.connect() # aqui se establece la conexion a la base de datos
    print("Conexión exitosa")
except Exception as e:
    print("Error al conectar:", e)

Conexión exitosa

In [25]:
df_departments.to_sql('departments_2',conexion, index=False)

7

In [27]:
pd.read_sql_table('departments_2',conexion)

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
6              8          Sports