In [1]:
! pip install mysql-connector-python==9.1.0

Collecting mysql-connector-python==9.1.0
  Downloading mysql_connector_python-9.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Downloading mysql_connector_python-9.1.0-cp312-cp312-manylinux_2_28_x86_64.whl (34.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 38.5 MB/s  0:00:00m0:00:0100:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.1.0

In [2]:
! pip install SQLAlchemy==2.0.36

Collecting SQLAlchemy==2.0.36
  Downloading SQLAlchemy-2.0.36-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.7 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from SQLAlchemy==2.0.36) (4.15.0)
Collecting greenlet!=0.4.17 (from SQLAlchemy==2.0.36)
  Downloading greenlet-3.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Downloading SQLAlchemy-2.0.36-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 16.9 MB/s  0:00:00 eta 0:00:01
Downloading greenlet-3.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (609 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 609.9/609.9 kB 16.7 MB/s  0:00:00
Installing collected packages: greenlet, SQLAlchemy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [SQLAlchemy]2 [SQLAlchemy]
Successfully installed SQLAlchemy-2.0.36 greenlet-3.3.0

In [8]:
import sqlalchemy as db 
import pandas as pd

In [12]:
#engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3306/retail_db') # Cadena de conexion a MySQL
engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3310/retail_db')
try:
    conexion = engine.connect() # aqui se establece la conexion a la base de datos
    print("Conexión exitosa")
except Exception as e:
    print("Error al conectar:", e)

Conexión exitosa

In [ ]:
df_departments = pd.read_sql_table('departments', conexion) # Si se lee la tabla completa 
df_departments

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [14]:
df_departments = pd.read_sql_query("SELECT * FROM departments", conexion) 

df_departments # imprimimos

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [15]:
df_departments = pd.read_sql("SELECT * FROM departments", conexion)

df_departments

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop